const vencedoresBolaDeOuro = [
  { ano: 2025, nome: "Ousmane Dembélé", pais: "🇫🇷 França", clube: "PSG", foto: "imagem43.png", descricao: "Melhor jogador da Champions League e da sua liga." },
  { ano: 2024, nome: "Rodri", pais: "🇪🇸 Espanha", clube: "Manchester City", foto: "imagem44.png", descricao: "Pilar do meio-campo do City campeão da Premier League e da Espanha campeã da Euro 2024." },
  { ano: 2023, nome: "Lionel Messi", pais: "🇦🇷 Argentina", clube: "Inter Miami", foto: "imagem85.png", descricao: "Campeão do mundo 2022 com a Argentina. 21 gols e 20 assistências na temporada." },
  { ano: 2022, nome: "Karim Benzema", pais: "🇫🇷 França", clube: "Real Madrid", foto: "imagem45.png", descricao: "Artilheiro da Champions 21/22 com 15 gols. Liderou o Real ao título europeu." },
  { ano: 2021, nome: "Lionel Messi", pais: "🇦🇷 Argentina", clube: "PSG", foto: "imagem85.png", descricao: "Campeão da Copa América com a Argentina. 38 gols e 14 assistências na temporada." },
  { ano: 2019, nome: "Lionel Messi", pais: "🇦🇷 Argentina", clube: "Barcelona", foto: "imagem85.png", descricao: "51 gols e 22 assistências. Artilheiro da La Liga e da Champions." },
  { ano: 2018, nome: "Luka Modrić", pais: "🇭🇷 Croácia", clube: "Real Madrid", foto: "imagem46.png", descricao: "Campeão da Champions e vice da Copa do Mundo. Melhor jogador do Mundial." },
  { ano: 2017, nome: "Cristiano Ronaldo", pais: "🇵🇹 Portugal", clube: "Real Madrid", foto: "imagem84.png", descricao: "Artilheiro da Champions com 12 gols. Campeão europeu e de La Liga." },
  { ano: 2016, nome: "Cristiano Ronaldo", pais: "🇵🇹 Portugal", clube: "Real Madrid", foto: "imagem84.png", descricao: "Campeão da Champions e da Euro 2016 com Portugal." },
  { ano: 2015, nome: "Lionel Messi", pais: "🇦🇷 Argentina", clube: "Barcelona", foto: "imagem85.png", descricao: "Triplete com o Barça. 58 gols e 27 assistências na temporada." },
  { ano: 2014, nome: "Cristiano Ronaldo", pais: "🇵🇹 Portugal", clube: "Real Madrid", foto: "imagem84.png", descricao: "17 gols na Champions, recorde. 61 gols na temporada." },
  { ano: 2013, nome: "Cristiano Ronaldo", pais: "🇵🇹 Portugal", clube: "Real Madrid", foto: "imagem84.png", descricao: "69 gols no ano. Campeão da Supercopa da Espanha." },
  { ano: 2012, nome: "Lionel Messi", pais: "🇦🇷 Argentina", clube: "Barcelona", foto: "imagem85.png", descricao: "91 gols no ano civil, recorde mundial. 50 gols na La Liga." },
  { ano: 2011, nome: "Lionel Messi", pais: "🇦🇷 Argentina", clube: "Barcelona", foto: "imagem85.png", descricao: "53 gols e 24 assistências. Campeão da Champions e La Liga." },
  { ano: 2010, nome: "Lionel Messi", pais: "🇦🇷 Argentina", clube: "Barcelona", foto: "imagem85.png", descricao: "47 gols na temporada. Campeão de La Liga." },
  { ano: 2009, nome: "Lionel Messi", pais: "🇦🇷 Argentina", clube: "Barcelona", foto: "imagem85.png", descricao: "38 gols. Campeão da Champions, La Liga e Copa do Rei." },
  { ano: 2008, nome: "Cristiano Ronaldo", pais: "🇵🇹 Portugal", clube: "Manchester United", foto: "imagem84.png", descricao: "42 gols. Campeão da Premier League e Champions." },
  { ano: 2007, nome: "Kaká", pais: "🇧🇷 Brasil", clube: "Milan", foto: "imagem47.png", descricao: "Artilheiro da Champions com 10 gols. Campeão europeu." },
  { ano: 2006, nome: "Fabio Cannavaro", pais: "🇮🇹 Itália", clube: "Real Madrid", foto: "imagem48.png", descricao: "Capitão da Itália campeã do mundo 2006. Defesa impecável." },
  { ano: 2005, nome: "Ronaldinho", pais: "🇧🇷 Brasil", clube: "Barcelona", foto: "imagem49.png", descricao: "26 gols e 20 assistências. Futebol arte no auge." },
  { ano: 2004, nome: "Andriy Shevchenko", pais: "🇺🇦 Ucrânia", clube: "Milan", foto: "imagem50.png", descricao: "24 gols na Serie A. Campeão italiano." },
  { ano: 2003, nome: "Pavel Nedvěd", pais: "🇨🇿 Rep. Tcheca", clube: "Juventus", foto: "imagem51.png", descricao: "Motor da Juventus finalista da Champions." },
  { ano: 2002, nome: "Ronaldo", pais: "🇧🇷 Brasil", clube: "Real Madrid", foto: "imagem18.png", descricao: "Campeão do mundo 2002. 8 gols na Copa." },
  { ano: 2001, nome: "Michael Owen", pais: "🏴󠁧󠁢󠁥󠁮󠁧󠁿 Inglaterra", clube: "Liverpool", foto: "imagem52.png", descricao: "Hat-trick contra a Alemanha. 24 gols na temporada." },
  { ano: 2000, nome: "Luís Figo", pais: "🇵🇹 Portugal", clube: "Real Madrid", foto: "imagem53.png", descricao: "Campeão de La Liga. 14 gols e 12 assistências." },
  { ano: 1999, nome: "Rivaldo", pais: "🇧🇷 Brasil", clube: "Barcelona", foto: "imagem54.png", descricao: "36 gols e 13 assistências. Campeão de La Liga." },
  { ano: 1998, nome: "Zinédine Zidane", pais: "🇫🇷 França", clube: "Juventus", foto: "imagem55.png", descricao: "Campeão do mundo 1998. 2 gols na final." },
  { ano: 1997, nome: "Ronaldo", pais: "🇧🇷 Brasil", clube: "Inter de Milão", foto: "imagem18.png", descricao: "47 gols na temporada. Fenômeno." },
  { ano: 1996, nome: "Matthias Sammer", pais: "🇩🇪 Alemanha", clube: "Borussia Dortmund", foto: "imagem56.png", descricao: "Campeão da Euro 1996. Líder da defesa alemã." },
  { ano: 1995, nome: "George Weah", pais: "🇱🇷 Libéria", clube: "Milan", foto: "imagem57.png", descricao: "Primeiro africano a ganhar. 29 gols na temporada." },
  { ano: 1994, nome: "Hristo Stoichkov", pais: "🇧🇬 Bulgária", clube: "Barcelona", foto: "imagem58.png", descricao: "Artilheiro da Copa 94 com 6 gols. 16 gols na La Liga." },
  { ano: 1993, nome: "Roberto Baggio", pais: "🇮🇹 Itália", clube: "Juventus", foto: "imagem59.png", descricao: "34 gols na temporada. Maestro da Juve." },
  { ano: 1992, nome: "Marco van Basten", pais: "🇳🇱 Holanda", clube: "Milan", foto: "imagem28.png", descricao: "25 gols. Campeão italiano invicto." },
  { ano: 1991, nome: "Jean-Pierre Papin", pais: "🇫🇷 França", clube: "Marseille", foto: "imagem60.png", descricao: "23 gols na Ligue 1. Artilheiro." },
  { ano: 1990, nome: "Lothar Matthäus", pais: "🇩🇪 Alemanha", clube: "Inter de Milão", foto: "imagem61.png", descricao: "Capitão da Alemanha campeã do mundo 1990." },
  { ano: 1989, nome: "Marco van Basten", pais: "🇳🇱 Holanda", clube: "Milan", foto: "imagem28.png", descricao: "19 gols. Campeão europeu com o Milan." },
  { ano: 1988, nome: "Marco van Basten", pais: "🇳🇱 Holanda", clube: "Milan", foto: "imagem28.png", descricao: "Campeão da Euro 88. Gol histórico na final." },
  { ano: 1987, nome: "Ruud Gullit", pais: "🇳🇱 Holanda", clube: "Milan", foto: "imagem62.png", descricao: "Líder do Milan e da Holanda campeã da Euro 88." },
  { ano: 1986, nome: "Igor Belanov", pais: "🇸🇺 URSS", clube: "Dínamo Kiev", foto: "imagem63.png", descricao: "Artilheiro da Copa 86. Campeão soviético." },
  { ano: 1985, nome: "Michel Platini", pais: "🇫🇷 França", clube: "Juventus", foto: "imagem64.png", descricao: "18 gols na Serie A. Campeão da Champions." },
  { ano: 1984, nome: "Michel Platini", pais: "🇫🇷 França", clube: "Juventus", foto: "imagem64.png", descricao: "Campeão da Euro 84. 20 gols na Serie A." },
  { ano: 1983, nome: "Michel Platini", pais: "🇫🇷 França", clube: "Juventus", foto: "imagem64.png", descricao: "16 gols na Serie A. Melhor jogador da Europa." },
  { ano: 1982, nome: "Paolo Rossi", pais: "🇮🇹 Itália", clube: "Juventus", foto: "imagem65.png", descricao: "6 gols na Copa 82. Campeão do mundo." },
  { ano: 1981, nome: "Karl-Heinz Rummenigge", pais: "🇩🇪 Alemanha Ocidental", clube: "Bayern Munique", foto: "imagem66.png", descricao: "29 gols na Bundesliga. Vice da Copa 82." },
  { ano: 1980, nome: "Karl-Heinz Rummenigge", pais: "🇩🇪 Alemanha Ocidental", clube: "Bayern Munique", foto: "imagem66.png", descricao: "26 gols na Bundesliga. Campeão europeu." },
  { ano: 1979, nome: "Kevin Keegan", pais: "🏴󠁧󠁢󠁥󠁮󠁧󠁿 Inglaterra", clube: "Hamburgo", foto: "imagem67.png", descricao: "Líder do Hamburgo campeão alemão." },
  { ano: 1978, nome: "Kevin Keegan", pais: "🏴󠁧󠁢󠁥󠁮󠁧󠁿 Inglaterra", clube: "Liverpool", foto: "imagem67.png", descricao: "Campeão europeu com o Liverpool." },
  { ano: 1977, nome: "Allan Simonsen", pais: "🇩🇰 Dinamarca", clube: "Borussia Mönchengladbach", foto: "imagem68.png", descricao: "Campeão da UEFA Cup. 18 gols na Bundesliga." },
  { ano: 1976, nome: "Franz Beckenbauer", pais: "🇩🇪 Alemanha Ocidental", clube: "Bayern Munique", foto: "imagem69.png", descricao: "Kaiser. Campeão europeu e mundial com o Bayern." },
  { ano: 1975, nome: "Oleg Blokhin", pais: "🇸🇺 URSS", clube: "Dínamo Kiev", foto: "imagem70.png", descricao: "Campeão da Recopa. 18 gols na liga soviética." },
  { ano: 1974, nome: "Johan Cruyff", pais: "🇳🇱 Holanda", clube: "Barcelona", foto: "imagem71.png", descricao: "Vice-campeão do mundo 74. Revolucionou o Barça." },
  { ano: 1973, nome: "Johan Cruyff", pais: "🇳🇱 Holanda", clube: "Barcelona", foto: "imagem71.png", descricao: "Campeão de La Liga. Futebol total." },
  { ano: 1972, nome: "Franz Beckenbauer", pais: "🇩🇪 Alemanha Ocidental", clube: "Bayern Munique", foto: "imagem69.png", descricao: "Campeão da Euro 72. Líder do Bayern." },
  { ano: 1971, nome: "Johan Cruyff", pais: "🇳🇱 Holanda", clube: "Ajax", foto: "imagem71.png", descricao: "Campeão europeu com o Ajax. 21 gols." },
  { ano: 1970, nome: "Gerd Müller", pais: "🇩🇪 Alemanha Ocidental", clube: "Bayern Munique", foto: "imagem40.png", descricao: "10 gols na Copa 70. Artilheiro nato." },
  { ano: 1969, nome: "Gianni Rivera", pais: "🇮🇹 Itália", clube: "Milan", foto: "imagem72.png", descricao: "Campeão europeu com o Milan." },
  { ano: 1968, nome: "George Best", pais: "🇬🇧 Irlanda do Norte", clube: "Manchester United", foto: "imagem73.png", descricao: "Campeão europeu. Drible e gols decisivos." },
  { ano: 1967, nome: "Flórián Albert", pais: "🇭🇺 Hungria", clube: "Ferencváros", foto: "imagem74.png", descricao: "Campeão húngaro. 25 gols na temporada." },
  { ano: 1966, nome: "Bobby Charlton", pais: "🏴󠁧󠁢󠁥󠁮󠁧󠁿 Inglaterra", clube: "Manchester United", foto: "imagem75.png", descricao: "Campeão do mundo 1966 com a Inglaterra." },
  { ano: 1965, nome: "Eusébio", pais: "🇵🇹 Portugal", clube: "Benfica", foto: "imagem39.png", descricao: "Artilheiro da Champions com 9 gols." },
  { ano: 1964, nome: "Denis Law", pais: "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Escócia", clube: "Manchester United", foto: "imagem76.png", descricao: "28 gols na temporada. Ídolo do United." },
  { ano: 1963, nome: "Lev Yashin", pais: "🇸🇺 URSS", clube: "Dínamo Moscou", foto: "imagem77.png", descricao: "Único goleiro a ganhar. A Aranha Negra." },
  { ano: 1962, nome: "Josef Masopust", pais: "🇨🇿 Tchecoslováquia", clube: "Dukla Praga", foto: "imagem78.png", descricao: "Vice-campeão do mundo 62. Meio-campo de classe." },
  { ano: 1961, nome: "Omar Sívori", pais: "🇮🇹 Itália", clube: "Juventus", foto: "imagem79.png", descricao: "25 gols na Serie A. Campeão italiano." },
  { ano: 1960, nome: "Luis Suárez", pais: "🇪🇸 Espanha", clube: "Barcelona", foto: "imagem80.png", descricao: "Único espanhol a ganhar. Maestro do Barça." },
  { ano: 1959, nome: "Alfredo Di Stéfano", pais: "🇪🇸 Espanha", clube: "Real Madrid", foto: "imagem81.png", descricao: "Campeão europeu. 23 gols na La Liga." },
  { ano: 1958, nome: "Raymond Kopa", pais: "🇫🇷 França", clube: "Real Madrid", foto: "imagem82.png", descricao: "Campeão europeu. 4º lugar na Copa 58." },
  { ano: 1957, nome: "Alfredo Di Stéfano", pais: "🇪🇸 Espanha", clube: "Real Madrid", foto: "imagem81.png", descricao: "Campeão europeu. 31 gols na temporada." },
  { ano: 1956, nome: "Stanley Matthews", pais: "🏴󠁧󠁢󠁥󠁮󠁧󠁿 Inglaterra", clube: "Blackpool", foto: "imagem83.png", descricao: "Primeiro vencedor. Lenda aos 41 anos." }
];