const vencedoresChuteiraDeOuro = [
  { ano: "2024/25", nome: "Kylian Mbappé", pais: "🇫🇷 França", clube: "PSG", foto: "imagem1.png", descricao: "31 gols na La Liga. Primeira Chuteira de Ouro da carreira." },
  { ano: "2023/24", nome: "Harry Kane", pais: "🏴󠁧󠁢󠁥󠁮󠁧󠁿 Inglaterra", clube: "Bayern Munique", foto: "imagem2.png", descricao: "36 gols na Bundesliga. Ganhou a Chuteira de Ouro Europeia 2023/24." },
  { ano: "2022/23", nome: "Erling Haaland", pais: "🇳🇴 Noruega", clube: "Manchester City", foto: "imagem3.png", descricao: "36 gols na Premier League. Recorde da era moderna em uma temporada." },
  { ano: "2021/22", nome: "Robert Lewandowski", pais: "🇵🇱 Polônia", clube: "Bayern Munique", foto: "imagem4.png", descricao: "35 gols na Bundesliga. Terceira Chuteira de Ouro." },
  { ano: "2020/21", nome: "Robert Lewandowski", pais: "🇵🇱 Polônia", clube: "Bayern Munique", foto: "imagem4.png", descricao: "41 gols na Bundesliga. Quebrou o recorde de Gerd Müller." },
  { ano: "2019/20", nome: "Ciro Immobile", pais: "🇮🇹 Itália", clube: "Lazio", foto: "imagem5.png", descricao: "36 gols na Serie A. Primeira Chuteira de um italiano desde 2007." },
  { ano: "2018/19", nome: "Lionel Messi", pais: "🇦🇷 Argentina", clube: "Barcelona", foto: "imagem6.png", descricao: "36 gols na La Liga. Sexta Chuteira de Ouro, recorde absoluto." },
  { ano: "2017/18", nome: "Lionel Messi", pais: "🇦🇷 Argentina", clube: "Barcelona", foto: "imagem6.png", descricao: "34 gols na La Liga. Quinta Chuteira de Ouro." },
  { ano: "2016/17", nome: "Lionel Messi", pais: "🇦🇷 Argentina", clube: "Barcelona", foto: "imagem6.png", descricao: "37 gols na La Liga. Quarta Chuteira de Ouro." },
  { ano: "2015/16", nome: "Luis Suárez", pais: "🇺🇾 Uruguai", clube: "Barcelona", foto: "imagem7.png", descricao: "40 gols na La Liga. Primeira Chuteira de Ouro." },
  { ano: "2014/15", nome: "Cristiano Ronaldo", pais: "🇵🇹 Portugal", clube: "Real Madrid", foto: "imagem8.png", descricao: "48 gols na La Liga. Quarta Chuteira de Ouro." },
  { ano: "2013/14", nome: "Luis Suárez", pais: "🇺🇾 Uruguai", clube: "Liverpool", foto: "imagem7.png", descricao: "31 gols na Premier League. Dividiu com Cristiano Ronaldo." },
  { ano: "2013/14", nome: "Cristiano Ronaldo", pais: "🇵🇹 Portugal", clube: "Real Madrid", foto: "imagem8.png", descricao: "31 gols na La Liga. Dividiu com Luis Suárez." },
  { ano: "2012/13", nome: "Lionel Messi", pais: "🇦🇷 Argentina", clube: "Barcelona", foto: "imagem6.png", descricao: "46 gols na La Liga. Terceira Chuteira de Ouro seguida." },
  { ano: "2011/12", nome: "Lionel Messi", pais: "🇦🇷 Argentina", clube: "Barcelona", foto: "imagem6.png", descricao: "50 gols na La Liga. Recorde da competição." },
  { ano: "2010/11", nome: "Cristiano Ronaldo", pais: "🇵🇹 Portugal", clube: "Real Madrid", foto: "imagem8.png", descricao: "40 gols na La Liga. Segunda Chuteira de Ouro." },
  { ano: "2009/10", nome: "Lionel Messi", pais: "🇦🇷 Argentina", clube: "Barcelona", foto: "imagem6.png", descricao: "34 gols na La Liga. Primeira Chuteira de Ouro." },
  { ano: "2008/09", nome: "Diego Forlán", pais: "🇺🇾 Uruguai", clube: "Atlético Madrid", foto: "imagem9.png", descricao: "32 gols na La Liga. Segunda Chuteira da carreira." },
  { ano: "2007/08", nome: "Cristiano Ronaldo", pais: "🇵🇹 Portugal", clube: "Manchester United", foto: "imagem8.png", descricao: "31 gols na Premier League. Primeira Chuteira de Ouro." },
  { ano: "2006/07", nome: "Francesco Totti", pais: "🇮🇹 Itália", clube: "Roma", foto: "imagem10.png", descricao: "26 gols na Serie A. Capitão e ídolo da Roma." },
  { ano: "2005/06", nome: "Luca Toni", pais: "🇮🇹 Itália", clube: "Fiorentina", foto: "imagem11.png", descricao: "31 gols na Serie A. Primeira Chuteira de Ouro." },
  { ano: "2004/05", nome: "Thierry Henry", pais: "🇫🇷 França", clube: "Arsenal", foto: "imagem12.png", descricao: "25 gols na Premier League. Dividiu com Diego Forlán." },
  { ano: "2004/05", nome: "Diego Forlán", pais: "🇺🇾 Uruguai", clube: "Villarreal", foto: "imagem9.png", descricao: "25 gols na La Liga. Dividiu com Thierry Henry." },
  { ano: "2003/04", nome: "Thierry Henry", pais: "🇫🇷 França", clube: "Arsenal", foto: "imagem12.png", descricao: "30 gols na Premier League. Primeira Chuteira de Ouro." },
  { ano: "2002/03", nome: "Roy Makaay", pais: "🇳🇱 Holanda", clube: "Deportivo La Coruña", foto: "imagem13.png", descricao: "29 gols na La Liga. Artilheiro surpresa." },
  { ano: "2001/02", nome: "Mário Jardel", pais: "🇧🇷 Brasil", clube: "Sporting", foto: "imagem14.png", descricao: "42 gols na Liga Portuguesa. Segunda Chuteira da carreira." },
  { ano: "2000/01", nome: "Henrik Larsson", pais: "🇸🇪 Suécia", clube: "Celtic", foto: "imagem15.png", descricao: "35 gols na Liga Escocesa. Primeira Chuteira de Ouro." },
  { ano: "1999/00", nome: "Kevin Phillips", pais: "🏴󠁧󠁢󠁥󠁮󠁧󠁿 Inglaterra", clube: "Sunderland", foto: "imagem16.png", descricao: "30 gols na Premier League. Primeira Chuteira de Ouro." },
  { ano: "1998/99", nome: "Mário Jardel", pais: "🇧🇷 Brasil", clube: "Porto", foto: "imagem14.png", descricao: "36 gols na Liga Portuguesa. Primeira Chuteira de Ouro." },
  { ano: "1997/98", nome: "Nikolaos Machlas", pais: "🇬🇷 Grécia", clube: "Vitesse", foto: "imagem17.png", descricao: "34 gols na Eredivisie. Primeira Chuteira de Ouro." },
  { ano: "1996/97", nome: "Ronaldo", pais: "🇧🇷 Brasil", clube: "Barcelona", foto: "imagem18.png", descricao: "34 gols na La Liga. Primeira Chuteira de Ouro." },
  { ano: "1995/96", nome: "Alan Shearer", pais: "🏴󠁧󠁢󠁥󠁮󠁧󠁿 Inglaterra", clube: "Blackburn Rovers", foto: "imagem19.png", descricao: "31 gols na Premier League. Primeira Chuteira de Ouro." },
  { ano: "1994/95", nome: "Arsen Avetisyan", pais: "🇦🇲 Armênia", clube: "Pyunik", foto: "imagem20.png", descricao: "39 gols na Liga Armênia." },
  { ano: "1993/94", nome: "David Taylor", pais: "🏴󠁧󠁢󠁷󠁬󠁳󠁿 País de Gales", clube: "Porthmadog", foto: "imagem21.png", descricao: "43 gols na Liga Galesa." },
  { ano: "1992/93", nome: "Ally McCoist", pais: "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Escócia", clube: "Rangers", foto: "imagem22.png", descricao: "34 gols na Liga Escocesa. Segunda Chuteira seguida." },
  { ano: "1991/92", nome: "Ally McCoist", pais: "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Escócia", clube: "Rangers", foto: "imagem22.png", descricao: "34 gols na Liga Escocesa. Primeira Chuteira de Ouro." },
  { ano: "1990/91", nome: "Darko Pančev", pais: "🇲🇰 Macedônia", clube: "Estrela Vermelha", foto: "imagem23.png", descricao: "34 gols na Liga Iugoslava." },
  { ano: "1989/90", nome: "Hugo Sánchez", pais: "🇲🇽 México", clube: "Real Madrid", foto: "imagem24.png", descricao: "38 gols na La Liga. Segunda Chuteira da carreira." },
  { ano: "1988/89", nome: "Dorinel Munteanu", pais: "🇷🇴 Romênia", clube: "Inter Sibiu", foto: "imagem25.png", descricao: "32 gols na Liga Romena." },
  { ano: "1987/88", nome: "Tanju Çolak", pais: "🇹🇷 Turquia", clube: "Galatasaray", foto: "imagem26.png", descricao: "39 gols na Liga Turca." },
  { ano: "1986/87", nome: "Rodion Cămătaru", pais: "🇷🇴 Romênia", clube: "Universitatea Craiova", foto: "imagem27.png", descricao: "44 gols na Liga Romena." },
  { ano: "1985/86", nome: "Marco van Basten", pais: "🇳🇱 Holanda", clube: "Ajax", foto: "imagem28.png", descricao: "37 gols na Eredivisie. Primeira Chuteira de Ouro." },
  { ano: "1984/85", nome: "Fernando Gomes", pais: "🇵🇹 Portugal", clube: "Porto", foto: "imagem29.png", descricao: "39 gols na Liga Portuguesa. Segunda Chuteira da carreira." },
  { ano: "1983/84", nome: "Ian Rush", pais: "🏴󠁧󠁢󠁷󠁬󠁳󠁿 País de Gales", clube: "Liverpool", foto: "imagem30.png", descricao: "32 gols na Primeira Divisão Inglesa." },
  { ano: "1982/83", nome: "Fernando Gomes", pais: "🇵🇹 Portugal", clube: "Porto", foto: "imagem29.png", descricao: "36 gols na Liga Portuguesa. Primeira Chuteira de Ouro." },
  { ano: "1981/82", nome: "Wim Kieft", pais: "🇳🇱 Holanda", clube: "PSV Eindhoven", foto: "imagem31.png", descricao: "32 gols na Eredivisie." },
  { ano: "1980/81", nome: "Georgi Slavkov", pais: "🇧🇬 Bulgária", clube: "Trakia Plovdiv", foto: "imagem32.png", descricao: "31 gols na Liga Búlgara." },
  { ano: "1979/80", nome: "Erwin Vandenbergh", pais: "🇧🇪 Bélgica", clube: "Lierse", foto: "imagem33.png", descricao: "39 gols na Liga Belga." },
  { ano: "1978/79", nome: "Keess Kist", pais: "🇳🇱 Holanda", clube: "AZ Alkmaar", foto: "imagem34.png", descricao: "34 gols na Eredivisie." },
  { ano: "1977/78", nome: "Hans Krankl", pais: "🇦🇹 Áustria", clube: "Rapid Viena", foto: "imagem35.png", descricao: "41 gols na Liga Austríaca." },
  { ano: "1976/77", nome: "Dudu Georgescu", pais: "🇷🇴 Romênia", clube: "Dinamo Bucareste", foto: "imagem36.png", descricao: "47 gols na Liga Romena. Segunda Chuteira seguida." },
  { ano: "1975/76", nome: "Sotiris Kaiafas", pais: "🇨🇾 Chipre", clube: "Omonia Nicosia", foto: "imagem37.png", descricao: "39 gols na Liga Cipriota." },
  { ano: "1974/75", nome: "Dudu Georgescu", pais: "🇷🇴 Romênia", clube: "Dinamo Bucareste", foto: "imagem36.png", descricao: "33 gols na Liga Romena. Primeira Chuteira de Ouro." },
  { ano: "1973/74", nome: "Héctor Yazalde", pais: "🇦🇷 Argentina", clube: "Sporting", foto: "imagem38.png", descricao: "46 gols na Liga Portuguesa." },
  { ano: "1972/73", nome: "Eusébio", pais: "🇵🇹 Portugal", clube: "Benfica", foto: "imagem39.png", descricao: "40 gols na Liga Portuguesa. Segunda Chuteira da carreira." },
  { ano: "1971/72", nome: "Gerd Müller", pais: "🇩🇪 Alemanha Ocidental", clube: "Bayern Munique", foto: "imagem40.png", descricao: "40 gols na Bundesliga. Primeira Chuteira de Ouro." },
  { ano: "1970/71", nome: "Josip Skoblar", pais: "🇭🇷 Iugoslávia", clube: "Marseille", foto: "imagem41.png", descricao: "44 gols na Ligue 1." },
  { ano: "1969/70", nome: "Gerd Müller", pais: "🇩🇪 Alemanha Ocidental", clube: "Bayern Munique", foto: "imagem40.png", descricao: "38 gols na Bundesliga." },
  { ano: "1968/69", nome: "Petar Zhekov", pais: "🇧🇬 Bulgária", clube: "CSKA Sófia", foto: "imagem42.png", descricao: "36 gols na Liga Búlgara." },
  { ano: "1967/68", nome: "Eusébio", pais: "🇵🇹 Portugal", clube: "Benfica", foto: "imagem39.png", descricao: "42 gols na Liga Portuguesa. Primeira Chuteira de Ouro." }
];